/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.nhom1.hrm.UI;

import javax.swing.ImageIcon;
import com.nhom1.hrm.Models.Department;
import com.nhom1.hrm.Models.Education;
import com.nhom1.hrm.Models.Gender;
import com.nhom1.hrm.Models.JobLevel;
import com.nhom1.hrm.UI.ComboBox.CustomColor;

/**
 *
 * @author Kris
 */
public class AppShell extends javax.swing.JFrame {

    /**
     * Creates new form AppShell
     */
    private String editingByEID = null;
    public AppShell() {
        initComponents();
        UpdateUI.LaFUI();
        CustomColor.setCustomRendererForAll(genderBox, lvlBox, eduBox, deptBox);
        Cards deck = new Cards();
        eSplitPane.setRightComponent(deck);
        deck.addCard("HOME", homePanel);
        deck.addCard("ABOUT", aboutPanel);
        deck.addCard("STATS", statsPanel);
        deck.showCard("HOME");
        SideBar.switchCardOnClick(homeButton, deck, "HOME");
        SideBar.switchCardOnClick(statsButton, deck, "STATS");
        MenuBar.aboutSwitchCardOnClick(aboutMenuItem, deck, "ABOUT");
        
        AfterInit.setgetComboBox(deptBox, lvlBox, eduBox, genderBox, eTable, addButton, delButton);
        try {
            UiTable.loadTable(eTable);
        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Error Loading Table: " + e.getMessage());
        }
        
        //Set App Icon when run
        //D:\Coding\Java\HRM-Project\HRM\src\main\java\com\nhom1\hrm\Asset\appIconf.png
        setIconImage(new ImageIcon(getClass().getResource("/com/nhom1/hrm/Asset/hr-manager.png")).getImage());

        setDefaultCloseOperation(EXIT_ON_CLOSE);
        KeyBind.bindEscToClose(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eSplitPane = new javax.swing.JSplitPane();
        sidePanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        homeButton = new javax.swing.JButton();
        statsButton = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();
        statsPanel = new javax.swing.JPanel();
        genderPanel = new javax.swing.JPanel();
        eduPanel = new javax.swing.JPanel();
        deptPanel = new javax.swing.JPanel();
        lvlPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        salaryLabel = new javax.swing.JLabel();
        eduLabel = new javax.swing.JLabel();
        lvlLabel = new javax.swing.JLabel();
        deptLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        mailLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        deptBox = new javax.swing.JComboBox<>();
        lvlBox = new javax.swing.JComboBox<>();
        eduBox = new javax.swing.JComboBox<>();
        phoneField = new javax.swing.JTextField();
        mailField = new javax.swing.JTextField();
        salaryField = new javax.swing.JTextField();
        eScrollPane = new javax.swing.JScrollPane();
        eTable = new javax.swing.JTable();
        addButton = new javax.swing.JButton();
        delButton = new javax.swing.JButton();
        genderLabel = new javax.swing.JLabel();
        genderBox = new javax.swing.JComboBox<>();
        nameField = new javax.swing.JTextField();
        ad_dressField = new javax.swing.JTextField();
        updateButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        aboutPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        eMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exportMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        selectedMenuItem = new javax.swing.JMenuItem();
        userMenu = new javax.swing.JMenu();
        logOutMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        eSplitPane.setDividerLocation(100);
        eSplitPane.setOneTouchExpandable(true);
        eSplitPane.setOpaque(false);

        sidePanel.setBackground(new java.awt.Color(0, 133, 245));
        sidePanel.setLayout(new java.awt.GridLayout(10, 1));

        logoLabel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        logoLabel.setForeground(new java.awt.Color(255, 255, 255));
        logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom1/hrm/Asset/hr-manager70.png"))); // NOI18N
        sidePanel.add(logoLabel);

        homeButton.setBackground(new java.awt.Color(0, 133, 245));
        homeButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        homeButton.setForeground(new java.awt.Color(255, 255, 255));
        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom1/hrm/Asset/home20.png"))); // NOI18N
        homeButton.setText("HOME");
        homeButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        homeButton.setFocusPainted(false);
        homeButton.setIconTextGap(6);
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        sidePanel.add(homeButton);

        statsButton.setBackground(new java.awt.Color(0, 133, 245));
        statsButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        statsButton.setForeground(new java.awt.Color(255, 255, 255));
        statsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom1/hrm/Asset/pie-chart20.png"))); // NOI18N
        statsButton.setText("STATS");
        statsButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        statsButton.setFocusPainted(false);
        statsButton.setIconTextGap(6);
        statsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statsButtonActionPerformed(evt);
            }
        });
        sidePanel.add(statsButton);

        eSplitPane.setLeftComponent(sidePanel);

        contentPanel.setBackground(new java.awt.Color(51, 204, 255));
        contentPanel.setLayout(new java.awt.CardLayout());

        statsPanel.setLayout(new java.awt.GridLayout(2, 2, 8, 8));

        genderPanel.setBackground(new java.awt.Color(255, 204, 102));

        javax.swing.GroupLayout genderPanelLayout = new javax.swing.GroupLayout(genderPanel);
        genderPanel.setLayout(genderPanelLayout);
        genderPanelLayout.setHorizontalGroup(
            genderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );
        genderPanelLayout.setVerticalGroup(
            genderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 441, Short.MAX_VALUE)
        );

        statsPanel.add(genderPanel);

        eduPanel.setBackground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout eduPanelLayout = new javax.swing.GroupLayout(eduPanel);
        eduPanel.setLayout(eduPanelLayout);
        eduPanelLayout.setHorizontalGroup(
            eduPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );
        eduPanelLayout.setVerticalGroup(
            eduPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 441, Short.MAX_VALUE)
        );

        statsPanel.add(eduPanel);

        deptPanel.setBackground(new java.awt.Color(204, 255, 0));

        javax.swing.GroupLayout deptPanelLayout = new javax.swing.GroupLayout(deptPanel);
        deptPanel.setLayout(deptPanelLayout);
        deptPanelLayout.setHorizontalGroup(
            deptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );
        deptPanelLayout.setVerticalGroup(
            deptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 441, Short.MAX_VALUE)
        );

        statsPanel.add(deptPanel);

        lvlPanel.setBackground(new java.awt.Color(51, 0, 255));

        javax.swing.GroupLayout lvlPanelLayout = new javax.swing.GroupLayout(lvlPanel);
        lvlPanel.setLayout(lvlPanelLayout);
        lvlPanelLayout.setHorizontalGroup(
            lvlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );
        lvlPanelLayout.setVerticalGroup(
            lvlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 441, Short.MAX_VALUE)
        );

        statsPanel.add(lvlPanel);

        contentPanel.add(statsPanel, "card3");

        homePanel.setBackground(new java.awt.Color(255, 255, 255));

        titleLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        titleLabel.setText("EMPLOYEE MANAGEMENT");

        nameLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        nameLabel.setText("Name:");

        salaryLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        salaryLabel.setText("Salary:");

        eduLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        eduLabel.setText("Education");

        lvlLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lvlLabel.setText("Level:");

        deptLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        deptLabel.setText("Department:");

        phoneLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        phoneLabel.setText("Phone");

        mailLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        mailLabel.setText("Email:");

        dateLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        dateLabel.setText("Address");

        eTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        eScrollPane.setViewportView(eTable);

        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom1/hrm/Asset/checked14.png"))); // NOI18N
        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        delButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom1/hrm/Asset/cancel14.png"))); // NOI18N
        delButton.setText("DELETE");
        delButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delButtonActionPerformed(evt);
            }
        });

        genderLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        genderLabel.setText("Gender:");

        genderBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderBoxActionPerformed(evt);
            }
        });

        updateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom1/hrm/Asset/refresh14.png"))); // NOI18N
        updateButton.setText("UPDATE");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom1/hrm/Asset/exclamation-mark14.png"))); // NOI18N
        searchButton.setText("SEARCH");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        refreshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom1/hrm/Asset/reload14.png"))); // NOI18N
        refreshButton.setText("REFRESH");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eduLabel)
                    .addComponent(dateLabel)
                    .addComponent(phoneLabel)
                    .addComponent(mailLabel)
                    .addComponent(nameLabel))
                .addGap(12, 12, 12)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(homePanelLayout.createSequentialGroup()
                                .addComponent(eduBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nameField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                    .addComponent(ad_dressField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(phoneField))
                                .addGap(215, 215, 215)))
                        .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(homePanelLayout.createSequentialGroup()
                                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(genderLabel)
                                    .addComponent(deptLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(deptBox, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(genderBox, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(homePanelLayout.createSequentialGroup()
                                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lvlLabel)
                                    .addComponent(salaryLabel))
                                .addGap(38, 38, 38)
                                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lvlBox, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(salaryField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(188, 188, 188))
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addComponent(mailField)
                        .addGap(45, 45, 45)
                        .addComponent(addButton)
                        .addGap(18, 18, 18)
                        .addComponent(delButton)
                        .addGap(18, 18, 18)
                        .addComponent(updateButton)
                        .addGap(18, 18, 18)
                        .addComponent(searchButton)
                        .addGap(18, 18, 18)
                        .addComponent(refreshButton)
                        .addGap(43, 43, 43))))
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(titleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(eScrollPane)
                .addContainerGap())
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addGap(27, 27, 27)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(genderLabel)
                    .addComponent(genderBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deptLabel)
                    .addComponent(dateLabel)
                    .addComponent(deptBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ad_dressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lvlLabel)
                    .addComponent(eduLabel)
                    .addComponent(lvlBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eduBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salaryLabel)
                    .addComponent(phoneLabel)
                    .addComponent(salaryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mailLabel)
                            .addComponent(mailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addButton)
                            .addComponent(delButton)
                            .addComponent(updateButton)
                            .addComponent(searchButton)
                            .addComponent(refreshButton))
                        .addGap(12, 12, 12)))
                .addComponent(eScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        contentPanel.add(homePanel, "card2");

        jLabel2.setText("Team 1 project");

        javax.swing.GroupLayout aboutPanelLayout = new javax.swing.GroupLayout(aboutPanel);
        aboutPanel.setLayout(aboutPanelLayout);
        aboutPanelLayout.setHorizontalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(781, Short.MAX_VALUE))
        );
        aboutPanelLayout.setVerticalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(868, Short.MAX_VALUE))
        );

        contentPanel.add(aboutPanel, "card3");

        eSplitPane.setRightComponent(contentPanel);

        getContentPane().add(eSplitPane, java.awt.BorderLayout.CENTER);

        fileMenu.setText("File");

        exportMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom1/hrm/Asset/upload14.png"))); // NOI18N
        exportMenuItem.setText("Export");
        exportMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exportMenuItem);

        eMenuBar.add(fileMenu);

        editMenu.setText("Edit");

        selectedMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom1/hrm/Asset/checked14.png"))); // NOI18N
        selectedMenuItem.setText("Selected");
        selectedMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectedMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(selectedMenuItem);

        eMenuBar.add(editMenu);

        userMenu.setText("User");

        logOutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom1/hrm/Asset/log-out14.png"))); // NOI18N
        logOutMenuItem.setText("Log Out");
        logOutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutMenuItemActionPerformed(evt);
            }
        });
        userMenu.add(logOutMenuItem);

        eMenuBar.add(userMenu);

        helpMenu.setText("Help");

        aboutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom1/hrm/Asset/question-mark-14.png"))); // NOI18N
        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        eMenuBar.add(helpMenu);

        setJMenuBar(eMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        ButtonAtcion.onAdd(nameField, eduBox, deptBox, lvlBox, genderBox, phoneField, mailField, salaryField, eTable);
    }//GEN-LAST:event_addButtonActionPerformed

    private void delButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delButtonActionPerformed
        // TODO add your handling code here:
        ButtonAtcion.onDelete(eTable);
    }//GEN-LAST:event_delButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeButtonActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void genderBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderBoxActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        ButtonAtcion.onUpdate(editingByEID, nameField, eduBox, deptBox, lvlBox, genderBox, phoneField, mailField, salaryField, eTable);
        editingByEID = null;
    }//GEN-LAST:event_updateButtonActionPerformed

    private void selectedMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectedMenuItemActionPerformed
        // TODO add your handling code here:
        editingByEID = MenuBar.onSelected(eTable, nameField, ad_dressField, eduBox, deptBox, lvlBox, genderBox, phoneField, mailField, salaryField);
    }//GEN-LAST:event_selectedMenuItemActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        ButtonAtcion.onSearch(nameField, eduBox, deptBox, lvlBox, genderBox, phoneField, mailField, salaryField, eTable);
    }//GEN-LAST:event_searchButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
        ButtonAtcion.onRefresh(nameField, eduBox, deptBox, lvlBox, genderBox, phoneField, mailField, salaryField, eTable);
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void exportMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportMenuItemActionPerformed
        // TODO add your handling code here:
        MenuBar.onExport(this, eTable);
    }//GEN-LAST:event_exportMenuItemActionPerformed

    private void logOutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutMenuItemActionPerformed
        // TODO add your handling code here:
        MenuBar.onLogoutAndRelaunch(this, null, AppShell::new , true);
    }//GEN-LAST:event_logOutMenuItemActionPerformed

    private void statsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statsButtonActionPerformed
        // TODO add your handling code here:
        //Stats Charts
        StatsCharts.loadGenderChartInto(genderPanel);
        StatsCharts.loadDepartmentChartInto(deptPanel);
        StatsCharts.loadJobLevelChartInto(lvlPanel);
        StatsCharts.loadEducationChartInto(eduPanel);
    }//GEN-LAST:event_statsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppShell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppShell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppShell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppShell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppShell().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JPanel aboutPanel;
    private javax.swing.JTextField ad_dressField;
    private javax.swing.JButton addButton;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JButton delButton;
    private javax.swing.JComboBox<Department> deptBox;
    private javax.swing.JLabel deptLabel;
    private javax.swing.JPanel deptPanel;
    private javax.swing.JMenuBar eMenuBar;
    private javax.swing.JScrollPane eScrollPane;
    private javax.swing.JSplitPane eSplitPane;
    private javax.swing.JTable eTable;
    private javax.swing.JMenu editMenu;
    private javax.swing.JComboBox<Education> eduBox;
    private javax.swing.JLabel eduLabel;
    private javax.swing.JPanel eduPanel;
    private javax.swing.JMenuItem exportMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JComboBox<Gender> genderBox;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JPanel genderPanel;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JButton homeButton;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem logOutMenuItem;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JComboBox<JobLevel> lvlBox;
    private javax.swing.JLabel lvlLabel;
    private javax.swing.JPanel lvlPanel;
    private javax.swing.JTextField mailField;
    private javax.swing.JLabel mailLabel;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField phoneField;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JButton refreshButton;
    private javax.swing.JTextField salaryField;
    private javax.swing.JLabel salaryLabel;
    private javax.swing.JButton searchButton;
    private javax.swing.JMenuItem selectedMenuItem;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JButton statsButton;
    private javax.swing.JPanel statsPanel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton updateButton;
    private javax.swing.JMenu userMenu;
    // End of variables declaration//GEN-END:variables
}
